/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/



function sumEvenFibNumbers(maxNumber){
  var first = 1;
  var second = 2; 
  var sum = 0; 
  while(second <= maxNumber){
    // console.log('first', first);
    // console.log('second', second);
    if( second % 2 === 0 ){
      sum += second; 
    }
    var oldSecond = second; 
    second = first + second;
    first = oldSecond; 
  }
  return sum; 
}

console.log('sum ' , sumEvenFibNumbers(4000000));